query GetMyProfile @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  user(key: {id_expr: "auth.uid"}) {
    id
    username
    displayName
    email
    photoUrl
    statusMessage
    lastOnline
    createdAt
  }
}

mutation SendMessage($receiverId: UUID!, $content: String!, $messageType: String!) @auth(level: USER) {
  message_insert(data: {
    senderId_expr: "auth.uid",
    receiverId: $receiverId,
    content: $content,
    messageType: $messageType,
    createdAt_expr: "request.time"
  })
}

query GetMyContacts @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users.") {
  contacts_on_owner(where: {ownerId: {eq_expr: "auth.uid"}}) {
    contactUser {
      id
      username
      displayName
      photoUrl
    }
    nickname
    createdAt
  }
}

mutation CreateNewUser($username: String!, $email: String!, $passwordHash: String!, $displayName: String, $photoUrl: String, $statusMessage: String) @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  user_insert(data: {
    username: $username,
    email: $email,
    passwordHash: $passwordHash,
    createdAt_expr: "request.time",
    displayName: $displayName,
    photoUrl: $photoUrl,
    statusMessage: $statusMessage
  })
}